version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sales-ai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: autobahn
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend:
    build: .
    container_name: sales-ai_backend
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/autobahn
      PYTHONPATH: /app
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge